In [1]:
import numpy as np

In [15]:
import queue

In [44]:
import math

In [20]:
graph = -np.random.randint(2, size = (10,10))

In [27]:
graph

array([[-1,  0, -1,  0,  0,  0,  0, -1, -1, -1],
       [ 0,  0,  0,  0,  0, -1, -1,  0,  0,  0],
       [ 0, -1, -1,  0, -1,  0,  0,  0, -1, -1],
       [-1,  0, -1, -1,  0, -1, -1,  0, -1, -1],
       [-1,  0,  0, -1,  0,  0,  0, -1, -1,  0],
       [ 0, -1, -1,  0, -1,  0, -1, -1,  0, -1],
       [-1, -1,  0,  0,  0, -1,  0, -1, -1, -1],
       [ 0,  0, -1,  0,  0,  0, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1,  0, -1,  0,  0, -1],
       [ 0, -1,  0, -1,  0,  0, -1, -1, -1, -1]])

In [8]:
start = (2,1)

In [25]:
DIRECTIONS = [(-1, 0), (-1, -1), (0, 1), (1, 1), (1,  0), (1, -1), (0, -1), (-1, -1)]

In [32]:
def isValidPoint(graph, p):
    i, j = p
    if i < 0 or i >= graph.shape[0]:
        return False
    if j < 0 or j >= graph.shape[1]:
        return False
    return True

In [37]:
def breadth_first(graph, start, end):
    graph = np.copy(graph)
    q = queue.Queue()
    q.put(start)
    while not q.empty():
        curr = q.get()
        for i, direction in enumerate(DIRECTIONS):
            nextLoc = (curr[0] + direction[0], curr[1] + direction[1])
            if isValidPoint(graph, nextLoc) and graph[nextLoc[0], nextLoc[1]] == 0:
                q.put(nextLoc)
                graph[nextLoc[0], nextLoc[1]] = i + 1
                if nextLoc == end:
                    return graph
        print(graph)
    return graph

In [38]:
breadth_first(graph, (2,1), (5,5))

[[-1  0 -1  0  0  0  0 -1 -1 -1]
 [ 2  1  0  0  0 -1 -1  0  0  0]
 [ 7 -1 -1  0 -1  0  0  0 -1 -1]
 [-1  5 -1 -1  0 -1 -1  0 -1 -1]
 [-1  0  0 -1  0  0  0 -1 -1  0]
 [ 0 -1 -1  0 -1  0 -1 -1  0 -1]
 [-1 -1  0  0  0 -1  0 -1 -1 -1]
 [ 0  0 -1  0  0  0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0 -1  0 -1  0  0 -1 -1 -1 -1]]
[[-1  1 -1  0  0  0  0 -1 -1 -1]
 [ 2  1  3  0  0 -1 -1  0  0  0]
 [ 7 -1 -1  0 -1  0  0  0 -1 -1]
 [-1  5 -1 -1  0 -1 -1  0 -1 -1]
 [-1  0  0 -1  0  0  0 -1 -1  0]
 [ 0 -1 -1  0 -1  0 -1 -1  0 -1]
 [-1 -1  0  0  0 -1  0 -1 -1 -1]
 [ 0  0 -1  0  0  0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0 -1  0 -1  0  0 -1 -1 -1 -1]]
[[-1  1 -1  0  0  0  0 -1 -1 -1]
 [ 2  1  3  0  0 -1 -1  0  0  0]
 [ 7 -1 -1  0 -1  0  0  0 -1 -1]
 [-1  5 -1 -1  0 -1 -1  0 -1 -1]
 [-1  0  0 -1  0  0  0 -1 -1  0]
 [ 0 -1 -1  0 -1  0 -1 -1  0 -1]
 [-1 -1  0  0  0 -1  0 -1 -1 -1]
 [ 0  0 -1  0  0  0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0 -1  0 -1  0  0 -1 -1 -1 -1]]
[[-1  1

array([[-1,  1, -1,  1,  3,  3,  0, -1, -1, -1],
       [ 2,  1,  3,  3,  3, -1, -1,  0,  0,  0],
       [ 7, -1, -1,  4, -1,  4,  3,  0, -1, -1],
       [-1,  5, -1, -1,  4, -1, -1,  0, -1, -1],
       [-1,  5,  4, -1,  5,  4,  3, -1, -1,  0],
       [ 6, -1, -1,  4, -1,  5, -1, -1,  0, -1],
       [-1, -1,  6,  5,  4, -1,  0, -1, -1, -1],
       [ 0,  6, -1,  6,  5,  4, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1,  0, -1,  0,  0, -1],
       [ 0, -1,  0, -1,  0,  0, -1, -1, -1, -1]])

In [47]:
def djikstras(graph, start, end):
    graph = np.copy(graph)
    q = queue.PriorityQueue()
    q.put(start)
    cost_so_far = np.zeros(graph.shape)
    while not q.empty():
        curr = q.get()
        for i, direction in enumerate(DIRECTIONS):
            nextLoc = (curr[0] + direction[0], curr[1] + direction[1])
            cost = math.sqrt(direction[0] ** 2 + direction[1] ** 2)
            if isValidPoint(graph, nextLoc) and ((graph[nextLoc[0], nextLoc[1]] == 0) or (cost < cost_so_far[nextLoc[0], nextLoc[1]])):
                q.put(nextLoc, cost)
                graph[nextLoc[0], nextLoc[1]] = i + 1
                if nextLoc == end:
                    return graph
        print(graph)
    print(cost_so_far)
    return graph

In [48]:
djikstras(graph,(2,1), (5,5))

[[-1  0 -1  0  0  0  0 -1 -1 -1]
 [ 2  1  0  0  0 -1 -1  0  0  0]
 [ 7 -1 -1  0 -1  0  0  0 -1 -1]
 [-1  5 -1 -1  0 -1 -1  0 -1 -1]
 [-1  0  0 -1  0  0  0 -1 -1  0]
 [ 0 -1 -1  0 -1  0 -1 -1  0 -1]
 [-1 -1  0  0  0 -1  0 -1 -1 -1]
 [ 0  0 -1  0  0  0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0 -1  0 -1  0  0 -1 -1 -1 -1]]
[[-1  0 -1  0  0  0  0 -1 -1 -1]
 [ 2  1  0  0  0 -1 -1  0  0  0]
 [ 7 -1 -1  0 -1  0  0  0 -1 -1]
 [-1  5 -1 -1  0 -1 -1  0 -1 -1]
 [-1  0  0 -1  0  0  0 -1 -1  0]
 [ 0 -1 -1  0 -1  0 -1 -1  0 -1]
 [-1 -1  0  0  0 -1  0 -1 -1 -1]
 [ 0  0 -1  0  0  0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0 -1  0 -1  0  0 -1 -1 -1 -1]]
[[-1  1 -1  0  0  0  0 -1 -1 -1]
 [ 2  1  3  0  0 -1 -1  0  0  0]
 [ 7 -1 -1  0 -1  0  0  0 -1 -1]
 [-1  5 -1 -1  0 -1 -1  0 -1 -1]
 [-1  0  0 -1  0  0  0 -1 -1  0]
 [ 0 -1 -1  0 -1  0 -1 -1  0 -1]
 [-1 -1  0  0  0 -1  0 -1 -1 -1]
 [ 0  0 -1  0  0  0 -1 -1 -1  0]
 [-1 -1 -1 -1 -1  0 -1  0  0 -1]
 [ 0 -1  0 -1  0  0 -1 -1 -1 -1]]
[[-1  1

array([[-1,  1, -1,  1,  3,  3,  3, -1, -1, -1],
       [ 2,  1,  3,  3,  3, -1, -1,  4,  3,  3],
       [ 7, -1, -1,  4, -1,  4,  6,  5, -1, -1],
       [-1,  5, -1, -1,  4, -1, -1,  4, -1, -1],
       [-1,  5,  4, -1,  5,  4,  6, -1, -1,  0],
       [ 6, -1, -1,  4, -1,  4, -1, -1,  0, -1],
       [-1, -1,  0,  0,  0, -1,  0, -1, -1, -1],
       [ 0,  0, -1,  0,  0,  0, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1,  0, -1,  0,  0, -1],
       [ 0, -1,  0, -1,  0,  0, -1, -1, -1, -1]])