# Numpy Tutorial

<img src="https://imgs.xkcd.com/comics/machine_learning.png" width="40%" />

## Imports

In [1]:
import numpy as np

## Basics

In [3]:
A = np.array([1, 2, 3])

In [4]:
type(A)

numpy.ndarray

In [5]:
A.shape

(3,)

In [30]:
A * 2 + 3

array([5, 7, 9])

In [18]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
B.shape

(3, 3)

In [23]:
B[1, :]

array([4, 5, 6])

In [24]:
B[:, 1]

array([2, 5, 8])

In [25]:
B[1, 1]

5

In [26]:
B[1:, 1:]

array([[5, 6],
       [8, 9]])

## Helpful functions

In [27]:
B.sum()

45

In [44]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
B.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.c_[B, B]

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [37]:
np.r_[B, B]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Broadcasting 

In [39]:
A = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])

In [40]:
A == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [42]:
A[A == 0] = 2

In [43]:
A

array([[1, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [49]:
B = np.arange(1, 10)

In [50]:
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
B > 3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [53]:
B < 7

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [54]:
(B > 3) & (B < 7)

array([False, False, False,  True,  True,  True, False, False, False])

In [55]:
B[(B > 3) & (B < 7)] = 42

In [56]:
B

array([ 1,  2,  3, 42, 42, 42,  7,  8,  9])

## Additional Resources

* [Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/) (I used some parts of it while preparing this notebook)